title: CareerC2
description: The command and control platform for your career campaign.
author: Maurice Trammell

url: "https://zmauricetrammell.github.io"
baseurl: "/careerc2.github.io"

repository: zmauricetrammell/careerc2.github.io
